spring.application.name=order-service

server.port=${PORT:8082}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

customer-service.url=${CUSTOMER_SERVICE_URL:http://localhost:8081}
product-service.url=${PRODUCT_SERVICE_URL:http://localhost:8080}

spring.cloud.openfeign.httpclient.hc5.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
