spring.application.name=order-service

server.port=8082

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db_orders}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

customer-service.url=${CUSTOMER_SERVICE_URL:http://localhost:8081}
product-service.url=${PRODUCT_SERVICE_URL:http://localhost:8080}

spring.cloud.openfeign.httpclient.hc5.enabled=true
